// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Appointments
{
    public int AppointmentId { get; set; }

    public int? CustomerId { get; set; }

    public int? VehicleId { get; set; }

    public int? PackageId { get; set; }

    public DateTime? AppointmentDate { get; set; }

    public string Status { get; set; }

    public int? PromotionId { get; set; }

    public virtual Customers Customer { get; set; }

    public virtual Orders Orders { get; set; }

    public virtual ServicePackages Package { get; set; }

    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();

    public virtual Promotions Promotion { get; set; }

    public virtual ServiceHistory ServiceHistory { get; set; }

    public virtual ICollection<ServiceProgress> ServiceProgress { get; set; } = new List<ServiceProgress>();

    public virtual Vehicles Vehicle { get; set; }
}