// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class DayOffRequest
{
    public int RequestId { get; set; }

    public int StaffId { get; set; }

    public DateOnly RequestedDate { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateTime RequestedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public int? ApprovedByUserId { get; set; }

    public string AdminNotes { get; set; }

    public virtual User ApprovedByUser { get; set; }

    public virtual ServiceStaff Staff { get; set; }
}