// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class InventoryManagers
{
    public int ManagerId { get; set; }

    public virtual Users Manager { get; set; }
}