// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Orders
{
    public int OrderId { get; set; }

    public int? AppointmentId { get; set; }

    public int? PromotionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Appointments Appointment { get; set; }

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();

    public virtual Promotions Promotion { get; set; }
}