// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class PartsUsed
{
    public int UsedId { get; set; }

    public int? ServiceId { get; set; }

    public int? PartId { get; set; }

    public int? QuantityUsed { get; set; }

    public virtual Inventory Part { get; set; }

    public virtual ServiceHistory Service { get; set; }
}