// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Parts
{
    public int PartId { get; set; }

    public string PartName { get; set; }

    public int? Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public int? WarrantyMonths { get; set; }

    public virtual ICollection<PartPrices> PartPrices { get; set; } = new List<PartPrices>();

    public virtual ICollection<ServiceParts> ServiceParts { get; set; } = new List<ServiceParts>();

    public virtual ICollection<WarrantyClaims> WarrantyClaims { get; set; } = new List<WarrantyClaims>();
}