// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Payments
{
    public int PaymentId { get; set; }

    public int? AppointmentId { get; set; }

    public decimal? Amount { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime? PaidAt { get; set; }

    public int? OrderId { get; set; }

    public virtual Appointments Appointment { get; set; }

    public virtual Orders Order { get; set; }
}