// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class ServiceParts
{
    public int ServiceId { get; set; }

    public int PartId { get; set; }

    public int QuantityRequired { get; set; }

    public virtual Parts Part { get; set; }

    public virtual Services Service { get; set; }
}