// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class ServiceStaff
{
    public int StaffId { get; set; }

    public int UserId { get; set; }

    public string Specialty { get; set; }

    public string Experience { get; set; }

    public decimal? WorkingHours { get; set; }

    public decimal? Rating { get; set; }

    public string Avatar { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<DayOffRequest> DayOffRequests { get; set; } = new List<DayOffRequest>();

    public virtual ICollection<ServiceHistory> ServiceHistories { get; set; } = new List<ServiceHistory>();

    public virtual ICollection<StaffSchedule> StaffSchedules { get; set; } = new List<StaffSchedule>();

    public virtual User User { get; set; }
}