// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class ServiceStaff
{
    public int StaffId { get; set; }

    public decimal? WorkingHours { get; set; }

    public virtual ICollection<ServiceHistory> ServiceHistory { get; set; } = new List<ServiceHistory>();

    public virtual Users Staff { get; set; }
}