// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Services
{
    public int ServiceId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? EstimatedLaborHours { get; set; }

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

    public virtual ICollection<ServiceParts> ServiceParts { get; set; } = new List<ServiceParts>();

    public virtual ICollection<ServicePackages> Package { get; set; } = new List<ServicePackages>();
}