// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Users
{
    public int UserId { get; set; }

    public int? RoleId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string PasswordHash { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Customers Customers { get; set; }

    public virtual InventoryManagers InventoryManagers { get; set; }

    public virtual ICollection<Notifications> Notifications { get; set; } = new List<Notifications>();

    public virtual Roles Role { get; set; }

    public virtual ServiceStaff ServiceStaff { get; set; }
}