// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarServ.Domain.Entities;

public partial class Vehicles
{
    public int VehicleId { get; set; }

    public int? CustomerId { get; set; }

    public string LicensePlate { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public string Type { get; set; }

    public string Garage { get; set; }

    public int? Year { get; set; }

    public virtual ICollection<Appointments> Appointments { get; set; } = new List<Appointments>();

    public virtual Customers Customer { get; set; }
}